"""
FHIR Ingestion Pipeline - Project 1
Loads FHIR bundles from Snowflake internal stages into raw tables.

Architecture note: run_pipeline() will become an Airflow DAG in Project 2.
Each function maps to one Airflow task. Connection management will move
to SnowflakeHook. Config will move to Airflow Variables.
"""

# Imports always at module level
from dotenv import load_dotenv
from datetime import datetime
import json
import os
import uuid
import snowflake.connector

# ---------------------------------------------------------------------------
# Config — moves to Airflow Variables / config.py in Project 2
# ---------------------------------------------------------------------------

PIPELINE_CONFIG = {
    'organization': {
        'stage': '@HEALTHCARE_DEV.RAW.FHIR_ORGANIZATION_STAGE',
        'table': 'HEALTHCARE_DEV.RAW.ORGANIZATION'
    },
    'practitioner': {
        'stage': '@HEALTHCARE_DEV.RAW.FHIR_PRACTITIONER_STAGE',
        'table': 'HEALTHCARE_DEV.RAW.PRACTITIONER'
    },
    'patient': {
        'stage': '@HEALTHCARE_DEV.RAW.FHIR_PATIENT_STAGE',
        'table': 'HEALTHCARE_DEV.RAW.BUNDLE'
    }
}

MANIFEST_TABLE  = 'HEALTHCARE_DEV.RAW.LOAD_MANIFEST'
FILE_FORMAT     = 'HEALTHCARE_DEV.RAW.FHIR_JSON'

# ---------------------------------------------------------------------------
# Pipeline functions — each maps to one Airflow task in Project 2
# ---------------------------------------------------------------------------

def get_stage_metadata(cur, stage_name: str) -> dict:
    """
    LIST a Snowflake stage and return file count and total bytes.
    Refreshes directory metadata before listing.
    """
    # Refresh stage metadata cache before querying
    stage_bare = stage_name.replace('@', '')
    cur.execute(f"ALTER STAGE {stage_bare} REFRESH")

    cur.execute(f"LIST {stage_name}")
    rows = cur.fetchall()

    return {
        'file_count':   len(rows),
        'total_bytes':  sum(row[1] for row in rows)
    }


def insert_manifest_record(cur, load_id: str, stage_name: str,
                           file_count: int, total_bytes: int) -> None:
    """
    Insert a PENDING manifest record using a pre-generated load_id.
    load_id is generated by the caller to avoid race conditions.
    """
    cur.execute(
        f"""
        INSERT INTO {MANIFEST_TABLE}
            (load_id, stage_name, file_count, total_bytes, load_status)
        VALUES
            (%(load_id)s, %(stage_name)s, %(file_count)s,
             %(total_bytes)s, 'PENDING')
        """,
        {
            'load_id':      load_id,
            'stage_name':   stage_name,
            'file_count':   file_count,
            'total_bytes':  total_bytes
        }
    )


def copy_into_raw(cur, table_name: str, stage_name: str, load_id: str) -> dict:
    """
    Execute COPY INTO from stage to raw table.
    Uses CONTINUE to skip bad files rather than aborting the batch.
    Returns rows_loaded and rows_rejected from COPY INTO results.
    """
    cur.execute(
        f"""
        COPY INTO {table_name} (
            raw_bundle,
            load_id,
            source_filename,
            file_row_number
        )
        FROM (
            SELECT
                $1,
                '{load_id}',
                METADATA$FILENAME,
                METADATA$FILE_ROW_NUMBER
            FROM {stage_name}
        )
        FILE_FORMAT = (FORMAT_NAME = '{FILE_FORMAT}')
        ON_ERROR    = 'CONTINUE'
        PURGE       = FALSE
        """
    )

    rows = cur.fetchall()

    # COPY INTO returns either:
    # A) One row per file with full column set — new files were processed
    # B) Single status row with 1 column — no new files found (all already loaded)
    # Case B is not an error — it means the stage is current
    if not rows or len(rows[0]) < 4:
        rows_loaded   = 0
        rows_rejected = 0
    else:
        rows_loaded   = sum(r[3] for r in rows)
        rows_rejected = sum(r[5] for r in rows)

    return {
        'rows_loaded':   rows_loaded,
        'rows_rejected': rows_rejected
    }


def update_manifest_status(cur, load_id: str, status: str,
                           rows_loaded: int, rows_rejected: int,
                           error: Exception = None) -> None:
    """
    Update manifest record after COPY INTO completes or fails.
    Stores structured error payload as JSON string for queryability.
    """
    error_message = None
    if error:
        error_message = json.dumps({
            'error_type':    type(error).__name__,
            'error_message': str(error),
            'timestamp':     datetime.utcnow().isoformat()
        })

    cur.execute(
        f"""
        UPDATE {MANIFEST_TABLE}
        SET
            load_status   = %(status)s,
            rows_loaded   = %(rows_loaded)s,
            rows_rejected = %(rows_rejected)s,
            error_message = %(error_message)s
        WHERE load_id = %(load_id)s
        """,
        {
            'status':        status,
            'rows_loaded':   rows_loaded,
            'rows_rejected': rows_rejected,
            'error_message': error_message,
            'load_id':       load_id
        }
    )


def run_pipeline() -> None:
    """
    Orchestrates FHIR ingestion across all three stage/table pairs.
    Runs in dependency order: organization → practitioner → patient.
    This function becomes an Airflow DAG in Project 2.
    """
    load_dotenv()

    SNOWFLAKE_ACCOUNT   = os.getenv('SNOWFLAKE_ACCOUNT')
    SNOWFLAKE_USER      = os.getenv('SNOWFLAKE_USER')
    SNOWFLAKE_PASSWORD  = os.getenv('SNOWFLAKE_PASSWORD')
    SNOWFLAKE_ROLE      = os.getenv('SNOWFLAKE_ROLE')
    SNOWFLAKE_WAREHOUSE = os.getenv('SNOWFLAKE_WAREHOUSE')
    SNOWFLAKE_DATABASE  = os.getenv('SNOWFLAKE_DATABASE')
    SNOWFLAKE_SCHEMA    = os.getenv('SNOWFLAKE_SCHEMA')

    if not all([SNOWFLAKE_ACCOUNT, SNOWFLAKE_USER, SNOWFLAKE_PASSWORD,
                SNOWFLAKE_ROLE, SNOWFLAKE_WAREHOUSE, SNOWFLAKE_DATABASE,
                SNOWFLAKE_SCHEMA]):
        raise ValueError("One or more Snowflake credentials not set in .env")

    conn = None
    cur  = None

    try:
        conn = snowflake.connector.connect(
            account=SNOWFLAKE_ACCOUNT,
            user=SNOWFLAKE_USER,
            password=SNOWFLAKE_PASSWORD,
            role=SNOWFLAKE_ROLE,
            warehouse=SNOWFLAKE_WAREHOUSE,
            database=SNOWFLAKE_DATABASE,
            schema=SNOWFLAKE_SCHEMA
        )
        cur = conn.cursor()

        # Iterate in dependency order — org and practitioner before patient
        for resource_type, config in PIPELINE_CONFIG.items():
            stage = config['stage']
            table = config['table']

            # Generate load_id here — safe from race conditions
            load_id = str(uuid.uuid4())

            print(f"[{resource_type.upper()}] Starting load — load_id: {load_id}")

            try:
                # Step 1 — inspect stage
                metadata = get_stage_metadata(cur, stage)
                print(f"[{resource_type.upper()}] Files: {metadata['file_count']:,} "
                      f"| Bytes: {metadata['total_bytes']:,}")

                # Step 2 — write manifest record
                insert_manifest_record(
                    cur, load_id, stage,
                    metadata['file_count'],
                    metadata['total_bytes']
                )

                # Step 3 — load data
                result = copy_into_raw(cur, table, stage, load_id)

                # Step 4 — determine status
                if result['rows_loaded'] == 0 and result['rows_rejected'] == 0:
                    status = 'SKIPPED'  # no new files — not a failure
                elif result['rows_rejected'] == 0:
                    status = 'LOADED'
                elif result['rows_loaded'] > 0:
                    status = 'PARTIAL'
                else:
                    status = 'FAILED'

                # Step 5 — update manifest
                update_manifest_status(
                    cur, load_id, status,
                    result['rows_loaded'],
                    result['rows_rejected']
                )

                print(f"[{resource_type.upper()}] Status: {status} "
                      f"| Loaded: {result['rows_loaded']:,} "
                      f"| Rejected: {result['rows_rejected']:,}")

            except Exception as e:
                # Inner except — handles per-resource failures
                # Updates manifest to FAILED, then continues to next resource
                print(f"[{resource_type.upper()}] FAILED — {e}")
                try:
                    update_manifest_status(cur, load_id, 'FAILED', 0, 0, error=e)
                except Exception:
                    pass  # manifest update failed — don't mask original error
                raise  # re-raise so run_pipeline knows this resource failed

    finally:
        if cur:
            cur.close()
        if conn:
            conn.close()


if __name__ == '__main__':
    run_pipeline()